ec2cronjob-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16 workflow file created'

diff --git a/.github/workflows/ec2cronjob-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16.yaml b/.github/workflows/ec2cronjob-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16.yaml
--- a/.github/workflows/ec2cronjob-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16.yaml
+++ b/.github/workflows/ec2cronjob-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16.yaml
@@ -7,7 +7,7 @@ name: >-
       - main
   workflow_dispatch: {}
   repository_dispatch:
-    types: pipeline_78183e35-f2bf-4b78-891f-91f3700ce172
+    types: pipeline_95c8ea46-03e9-452a-bbcc-90a661c0a1c4
 env:
   ENCODED_PIPELINE_SECRET: >-
     ${{secrets.GWENIWIICK_ENV_2046883CF8A34774AE10510D8AB9865A_APP_AF24CA9B3F364036914BC78232AD5D16_EC2CRONJOBDEV_ENV_2046883CF8A34774AE10510D8AB9865A_APP_AF24CA9B3F364036914BC78232AD5D16}}
@@ -33,21 +33,215 @@ jobs:
       EC2_HOST: ${{ env.EC2_HOST }}
       EC2_INSTANCE_ID: ${{ env.EC2_INSTANCE_ID }}
     steps:
+      - name: 'Run :: Decoding Secrets 57149a63-403f-4046-ab2e-25d447c9ec68'
+        run: |2-
+
+                  if [ ! -x "$(command -v jq)" ]; then
+                    echo "jq not found, installing..."
+                    sudo apt-get update
+                    sudo apt-get install -y jq
+                  fi
+                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
+                
+      - name: 'Run :: Configure AWS credentials e9440738-51bc-46ec-bca2-68d19b45c654'
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ env.roleARN }}
+          role-session-name: skyu-pipeline-assume-role-session
+          aws-region: ${{ env.region }}
       - name: 'Run :: Create AWS Spot Instance'
         run: |2-
-              response=$(curl -X GET \
-                https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners \
-                -H 'Authorization: Bearer ${{ secrets.MY_TOKEN }}'
-              )
 
-              offline_skyu_runners=$(echo "$response" | jq '.runners | map(select(.status == "offline" and (.labels? | any(.name == "skyu"))))')
-              echo "RUNNERS :: $offline_skyu_runners"
+                # Get GitHub Actions runner registration token
+                response=$(curl -s -X POST         -H 'Accept: application/vnd.github+json'         -H 'Authorization: Bearer ${{ env.pat }}'         -H 'X-GitHub-Api-Version: 2022-11-28'         https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners/registration-token)
 
-              echo "Going to remove offline skyu runners..."
-              for runner in $(echo "$offline_skyu_runners" | jq -r '.[].id'); do
-                echo "Triggering action for runner ID: $runner"
-                curl -X DELETE \
-                https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners/$runner \
-                  -H 'Authorization: Bearer ${{ secrets.MY_TOKEN }}'
-              done
+                RUNNER_REG_TOKEN=$(echo "$response" | jq -r .token)
+                
+                if [ $RUNNER_REG_TOKEN != "null" ]; then
+                  USER_DATA="#!/bin/bash
+                  
+                  apt update && apt install -y apt-transport-https
+                  apt-get update && apt install docker.io -y
+                  echo \"Docker Installed\"
 
+                  usermod -aG docker ubuntu
+                  newgrp docker
+                  echo \"ubuntu Added to Groups\"
+
+                  # docker-compose
+                  curl -L 'https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64' -o /usr/local/bin/docker-compose
+                  echo \"Docker Compose Installed\"
+                  chmod +x /usr/local/bin/docker-compose
+                  echo \"Docker Compose Permissions added\"
+                  
+                  # Install GitHub Actions runner
+                  mkdir /home/ubuntu/actions-runner && cd /home/ubuntu/actions-runner
+                  curl -o actions-runner-linux-x64-2.312.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.312.0/actions-runner-linux-x64-2.312.0.tar.gz
+                  echo \"Github Runner Installed\"
+
+                  # Extract the installer
+                  tar xzf ./actions-runner-linux-x64-2.312.0.tar.gz
+                  echo \"Github Runner Installer Extracted\"
+                  
+                  # Run GitHub Actions runner configuration
+                  export RUNNER_ALLOW_RUNASROOT=1
+                  yes '' | ./config.sh --url https://github.com/${GITHUB_REPOSITORY} --token $RUNNER_REG_TOKEN --labels skyu
+                  echo \"Github Runner Configured\"
+                  
+                  # Run GitHub Actions runner
+                  yes '' | ./run.sh 
+                  echo \"Github Runner UP!\"
+                  "
+                  
+                  ENCODED_USER_DATA=$(echo -n "$USER_DATA" | sed 's/^[[:space:]]*//' | base64 -w 0)
+                  echo "ENCODED_USER_DATA :: $ENCODED_USER_DATA"
+                  echo "LAUNCH SPECIFICATION JSON :: {\"ImageId\":\"${{ env.EC2_IMAGE_ID }}\",\"InstanceType\":\"${{ env.EC2_INSTANCE_TYPE }}\",\"KeyName\":\"QWENKey\",\"SecurityGroupIds\":[\"${{ env.EC2_SECURITY_GROUP_ID }}\"],\"SubnetId\":\"${{ env.EC2_SUBNET_ID }}\",\"UserData\":\"$ENCODED_USER_DATA\"}"
+                  
+                  REQUEST_ID=$(aws ec2 request-spot-instances         --spot-price "${{ env.EC2_SPOT_INSTANCE_PRICE }}"         --instance-count 1         --type "one-time"         --launch-specification "{\"ImageId\":\"${{ env.EC2_IMAGE_ID }}\",\"InstanceType\":\"${{ env.EC2_INSTANCE_TYPE }}\",\"KeyName\":\"QWENKey\",\"SecurityGroupIds\":[\"${{ env.EC2_SECURITY_GROUP_ID }}\"],\"SubnetId\":\"${{ env.EC2_SUBNET_ID }}\",\"UserData\":\"$ENCODED_USER_DATA\"}"         --query 'SpotInstanceRequests[0].SpotInstanceRequestId'         --output text)
+                  aws ec2 wait spot-instance-request-fulfilled --spot-instance-request-ids $REQUEST_ID
+                  INSTANCE_ID=$(aws ec2 describe-spot-instance-requests --spot-instance-request-ids $REQUEST_ID --query 'SpotInstanceRequests[*].InstanceId' --output text)
+                  HOSTNAME=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
+                  
+                  echo "EC2_HOST=$HOSTNAME" >> $GITHUB_ENV
+                  echo "EC2_INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV 
+                else
+                    echo "$response"
+                  exit 1
+                fi
+              
+  compose-job:
+    name: Compose Job
+    permissions: write-all
+    runs-on: self-hosted
+    needs:
+      - start-runner
+    steps:
+      - name: Start
+        run: |2-
+
+              echo " Starting GitHub Action!" && 
+              echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
+              
+      - name: 'Run :: Checkout repository'
+        uses: actions/checkout@v2
+      - name: 'Run :: Checkout Specific Commit'
+        if: ${{ github.event.client_payload.commitId != null }}
+        run: git checkout ${{ github.event.client_payload.commitId }}
+      - name: 'Run :: Decoding Secrets 5284021f-e233-48f0-910f-4041eecd7e07'
+        run: |2-
+
+                  if [ ! -x "$(command -v jq)" ]; then
+                    echo "jq not found, installing..."
+                    sudo apt-get update
+                    sudo apt-get install -y jq
+                  fi
+                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
+                
+      - name: 'Run :: Configure AWS credentials 6f145c0c-448e-4701-86b7-b2aa13a5d97a'
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ env.roleARN }}
+          role-session-name: skyu-pipeline-assume-role-session
+          aws-region: ${{ env.region }}
+      - name: 'Run :: Docker Compose'
+        run: |2-
+
+              docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} build && docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} up -d &&
+              ${{env.ADDITIONAL_COMPOSE_COMMANDS}}
+              docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} down -v
+              
+      - name: 'Run :: Sync Outputs to S3 bucket'
+        run: |2-
+
+              if [ ! -x "$(command -v aws)" ]; then
+                echo "AWS CLI not found, installing..."
+                sudo apt update
+                sudo apt install -y awscli
+              fi
+
+              if aws s3api head-bucket --bucket skyu-client-reports 2>/dev/null; then
+                echo "Bucket skyu-client-reports exists."
+              # Create the S3 bucket if it doesn't exist
+              else
+                echo "Creating bucket skyu-client-reports..."
+                aws s3api create-bucket --bucket skyu-client-reports --region ${{ env.region }}
+              fi
+
+              aws s3 sync ${{ env.S3_SOURCE_PATH }} ${{ env.S3_SYNC_URL }}
+              
+  deploy:
+    name: Deploy
+    permissions: write-all
+    runs-on: ubuntu-latest
+    needs:
+      - compose-job
+    steps:
+      - name: 'Run :: Decoding Secrets 0da1da3f-9bca-4662-a7eb-4f43a854f2f3'
+        run: |2-
+
+                  if [ ! -x "$(command -v jq)" ]; then
+                    echo "jq not found, installing..."
+                    sudo apt-get update
+                    sudo apt-get install -y jq
+                  fi
+                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
+                
+      - name: 'Run :: Deploy and Notify Resource Service'
+        run: |2-
+
+              response=$(curl -d "appType=Deployment&imageRegistryURL=${{ env.IMAGE_NAME }}&appVersionId=${{ env.DEPLOYMENT_APP_VERSION_ID }}&tag=${{ env.IMAGE_TAG }}&containerName=${{ env.DEPLOYMENT_CONTAINER_NAME }}&shouldDeploy=${{env.DEPLOY_STEP_SHOULD_DEPLOY}}&pipelineRunId=${{ github.run_id }}&commitDetails[commitHash]=${{ github.sha }}&commitDetails[commitAvatar]=https://github.com/${{ github.event.head_commit.author.name }}.png&commitDetails[commitTime]=${{ github.event.head_commit.timestamp }}&commitDetails[commitMessage]=\"${{ github.event.head_commit.message }}\"&commitDetails[commitUser]=${{ github.event.head_commit.author.name }}" -X PATCH -H 'Authorization: ${{ env.SERVICE_ACC_ACCESS_TOKEN }}' -H 'x-organization-id: ${{ env.DEPLOYMENT_ORGANIZATION_ID }}' -H 'x-project-id: ${{ env.DEPLOYMENT_PROJECT_ID }}' -H 'x-environment-id: ${{ env.DEPLOYMENT_ENVIRONMENT_ID }}' -H 'x-application-id: ${{ env.DEPLOYMENT_APPLICATION_ID }}' -H 'x-auth-by: sa' -H 'Content-Type: application/x-www-form-urlencoded' '${{ env.DEPLOYMENT_ENDPOINT }}')
+              status_code=$?
+
+              if [ $status_code -eq 0 ]; then
+                if echo "$response" | grep -q '"success":true'; then
+                  echo "SUCCESS :: $response"
+                else
+                  echo "FAILED :: $response"
+                  exit 1
+                fi
+              else
+                echo "Failed to deploy. HTTP status code: $status_code"
+                exit 1
+              fi
+            
+  stop-runner:
+    name: Stop Runner
+    permissions: write-all
+    runs-on: ubuntu-latest
+    needs:
+      - start-runner
+      - compose-job
+    if: ${{ always() }}
+    steps:
+      - name: 'Run :: Decoding Secrets 502baf8d-4d94-4b53-820d-0dbae977d117'
+        run: |2-
+
+                  if [ ! -x "$(command -v jq)" ]; then
+                    echo "jq not found, installing..."
+                    sudo apt-get update
+                    sudo apt-get install -y jq
+                  fi
+                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
+                
+      - name: 'Run :: Configure AWS credentials 9d833f8a-5e83-47dc-8a22-f1c7a9828736'
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: ${{ env.roleARN }}
+          role-session-name: skyu-pipeline-assume-role-session
+          aws-region: ${{ env.region }}
+      - name: 'Run :: Stop AWS Spot Instance'
+        run: |2-
+
+                aws ec2 terminate-instances --instance-ids ${{ needs.start-runner.outputs.EC2_INSTANCE_ID }}
+
+                response=$(curl -X GET         https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners         -H 'Authorization: Bearer ${{ env.pat }}'
+                )
+                offline_skyu_runners=$(echo "$response" | jq '.runners | map(select(.status == "offline" and (.labels? | any(.name == "skyu"))))')
+                echo "Offline Skyu Runners :: $offline_skyu_runners"
+                
+                echo "Attempting to remove offline skyu runners..."
+                for runner in $(echo "$offline_skyu_runners" | jq -r '.[].id'); do
+                  echo "Triggering action for runner ID: $runner"
+                  curl -X DELETE         https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/runners/$runner           -H 'Authorization: Bearer ${{ env.pat }}'
+                done
+              
