gwen-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16 workflow file created'

diff --git a/.github/workflows/gwen-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16.yaml b/.github/workflows/gwen-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16.yaml
--- a/.github/workflows/gwen-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16.yaml
+++ b/.github/workflows/gwen-dev_env_2046883c-f8a3-4774-ae10-510d8ab9865a_app_af24ca9b-3f36-4036-914b-c78232ad5d16.yaml
@@ -7,30 +7,21 @@ name: >-
       - main
   workflow_dispatch: {}
   repository_dispatch:
-    types: pipeline_be3bc2dd-7d8c-4870-bb6f-d8bbd1a19e19
+    types: pipeline_32e46a96-6af9-44d5-a012-ff96d0a26526
 env:
   ENCODED_PIPELINE_SECRET: >-
     ${{secrets.GWENIWIICK_ENV_2046883CF8A34774AE10510D8AB9865A_APP_AF24CA9B3F364036914BC78232AD5D16_GWENDEV_ENV_2046883CF8A34774AE10510D8AB9865A_APP_AF24CA9B3F364036914BC78232AD5D16}}
-  EC2_INSTANCE_TYPE: t2.medium
-  EC2_IMAGE_ID: ami-0c7217cdde317cfec
-  EC2_SUBNET_ID: subnet-0511e49f8669e4d30
-  EC2_SECURITY_GROUP_ID: sg-0244f2edb7af33703
-  DOCKER_COMPOSE_FILE_PATH: gwen/docker-compose.yml
-  IMAGE_TAG: ${{github.event.client_payload.commitId || github.sha}}
-  WEB_APP_S3_SYNC_URL: >-
-    s3://skyu-client-reports/org_9f875a32-727f-4fb0-aeb6-ad3b32168642/project_88e61e3d-8f14-4fe8-b600-517e8138c28d/app_af24ca9b-3f36-4036-914b-c78232ad5d16/gwen_outputs/${{github.event.client_payload.commitId
-    || github.sha}}
   DEPLOY_STEP_SHOULD_DEPLOY: 'true'
 jobs:
   start-runner:
     name: Start Runner
     permissions: write-all
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     outputs:
-      label: ${{ steps.start-ec2-runner.outputs.label }}
-      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
+      EC2_HOST: ${{ env.EC2_HOST }}
+      EC2_INSTANCE_ID: ${{ env.EC2_INSTANCE_ID }}
     steps:
-      - name: 'Run :: Decoding Secrets 541e907b-6fc3-4571-984e-0f59e8cff30e'
+      - name: 'Run :: Decoding Secrets 6eeef1da-0a81-4b13-9a6d-d8cef267e731'
         run: |2-
 
                   if [ ! -x "$(command -v jq)" ]; then
@@ -40,39 +31,70 @@ jobs:
                   fi
                   echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                 
-      - name: 'Run :: Configure AWS credentials 83ed5edf-db1d-4f3b-b68d-a7c6d84453b1'
-        uses: aws-actions/configure-aws-credentials@v4
+      - name: 'Run :: Create AWS SSH with Permissions'
+        run: |2-
+
+              aws ec2 delete-key-pair --key-name QWENKey || true
+              aws ec2 create-key-pair --key-name QWENKey --query 'KeyMaterial' --output text >> $HOME/QWENKey.pem
+              chmod 600 $HOME/QWENKey.pem
+              cat $HOME/QWENKey.pem
+              
+      - name: 'Run :: Create AWS Spot Instance'
+        run: |2-
+
+              REQUEST_ID=$(aws ec2 request-spot-instances     --spot-price "${{ env.EC2_SPOT_INSTANCE_PRICE }}"     --instance-count 1     --type "one-time"     --launch-specification '{"ImageId":"ami-0c7217cdde317cfec","InstanceType":"${{ env.EC2_INSTANCE_TYPE }}","KeyName":"QWENKey"}'     --query 'SpotInstanceRequests[0].SpotInstanceRequestId'     --output text)
+              aws ec2 wait spot-instance-request-fulfilled --spot-instance-request-ids $REQUEST_ID
+              INSTANCE_ID=$(aws ec2 describe-spot-instance-requests --spot-instance-request-ids $REQUEST_ID --query 'SpotInstanceRequests[*].InstanceId' --output text)
+              HOSTNAME=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[0].Instances[0].PublicDnsName' --output text)
+              echo "EC2_HOST=$HOSTNAME" >> $GITHUB_ENV
+              echo "EC2_INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV 
+              
+      - name: 'Run :: Wait for SSH To be Available'
+        run: |2-
+
+              while ! nc -z ${{ env.EC2_HOST }} 22; do sleep 10; done
+              ssh -o StrictHostKeyChecking=no -i $HOME/QWENKey.pem ubuntu@${{ env.EC2_HOST }} '
+                ls -la ~/
+              '
+              
+      - name: 'Run :: Execute Commands on EC2'
+        uses: appleboy/ssh-action@master
         with:
-          role-to-assume: ${{ env.roleARN }}
-          role-session-name: skyu-pipeline-assume-role-session
-          aws-region: ${{ env.region }}
-      - name: 'Run :: Start EC2 Runner'
-        id: start-ec2-runner
-        uses: machulav/ec2-github-runner@v2
-        with:
-          mode: start
-          github-token: ${{ env.pat }}
-          ec2-instance-type: ${{ env.EC2_INSTANCE_TYPE }}
-          ec2-image-id: ${{ env.EC2_IMAGE_ID }}
-          subnet-id: ${{ env.EC2_SUBNET_ID }}
-          security-group-id: ${{ env.EC2_SECURITY_GROUP_ID }}
+          host: ${{ env.EC2_HOST }}
+          username: ubuntu
+          key_path: $HOME/QWENKey.pem
+          script: |2-
+
+                    sudo apt-get update
+                    sudo apt-get install -y docker.io
+                    sudo systemctl start docker
+                    sudo systemctl enable docker
+                    sudo groupadd docker
+                    sudo usermod -aG docker $USER
+                    newgrp docker
+                    # docker-compose
+                    sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+                    sudo chmod +x /usr/local/bin/docker-compose
+                  
   gwen-job:
     name: Gwen Job
     permissions: write-all
-    runs-on: ${{ needs.start-runner.outputs.label }}
+    runs-on: self-hosted
     needs:
       - start-runner
     steps:
       - name: Start
-        run: >-
-          echo " Starting GitHub Action!" && echo "IMAGE_EXISTS_IN_ECR=false" >>
-          $GITHUB_ENV
+        run: |2-
+
+              echo " Starting GitHub Action!" && 
+              echo "STEPS_CAN_PROCEED=true" >> $GITHUB_ENV
+              
       - name: 'Run :: Checkout repository'
         uses: actions/checkout@v2
       - name: 'Run :: Checkout Specific Commit'
         if: ${{ github.event.client_payload.commitId != null }}
         run: git checkout ${{ github.event.client_payload.commitId }}
-      - name: 'Run :: Decoding Secrets 52da6b8a-18b8-4237-8841-4ac0946688db'
+      - name: 'Run :: Decoding Secrets 26626e24-d1c3-4697-9c2b-d913e6e0f42f'
         run: |2-
 
                   if [ ! -x "$(command -v jq)" ]; then
@@ -82,45 +104,26 @@ jobs:
                   fi
                   echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                 
-      - name: 'Run :: Configure AWS credentials 867f22af-00b2-416d-ae1e-b979595d6d0a'
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ env.roleARN }}
-          role-session-name: skyu-pipeline-assume-role-session
-          aws-region: ${{ env.region }}
-      - name: 'Run :: Docker Compose'
+      - name: TESTINGGGGGGGGGGGGGGG
+        run: echo "HELLOOOOOOOOOOO"
+  deploy:
+    name: Deploy
+    permissions: write-all
+    runs-on: ubuntu-latest
+    needs:
+      - gwen-job
+    if: ${{ always() }}
+    steps:
+      - name: 'Run :: Decoding Secrets 5d2cf2b2-a779-4f1d-aac1-2c681bc43f36'
         run: |2-
 
-              echo "------------- Installing Docker Compose -------------" && 
-              sudo apt update && 
-              sudo apt install -y docker-compose && 
-              echo "------------- Running Docker Compose -------------" &&
-              docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} build && docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} up -d
-      - name: 'Run :: Gwen'
-        run: |2-
-
-              docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} run gwen &&
-              docker-compose -f ${{env.DOCKER_COMPOSE_FILE_PATH}} down -v
-              
-      - name: 'Run :: Sync Gwen Results to S3 bucket'
-        run: |2-
-
-              if [ ! -x "$(command -v aws)" ]; then
-                echo "AWS CLI not found, installing..."
-                sudo apt update
-                sudo apt install -y awscli
-              fi
-
-              if aws s3api head-bucket --bucket skyu-client-reports 2>/dev/null; then
-                echo "Bucket skyu-client-reports exists."
-              # Create the S3 bucket if it doesn't exist
-              else
-                echo "Creating bucket skyu-client-reports..."
-                aws s3api create-bucket --bucket skyu-client-reports --region ${{ env.region }}
-              fi
-
-              aws s3 sync ./gwen/output/reports ${{ env.WEB_APP_S3_SYNC_URL }}
-              
+                  if [ ! -x "$(command -v jq)" ]; then
+                    echo "jq not found, installing..."
+                    sudo apt-get update
+                    sudo apt-get install -y jq
+                  fi
+                  echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
+                
       - name: 'Run :: Deploy and Notify Resource Service'
         run: |2-
 
@@ -142,13 +145,13 @@ jobs:
   stop-runner:
     name: Stop Runner
     permissions: write-all
-    runs-on: ubuntu-latest
+    runs-on: self-hosted
     needs:
       - start-runner
       - gwen-job
     if: ${{ always() }}
     steps:
-      - name: 'Run :: Decoding Secrets 94bb9e01-5f47-49e8-bf59-85689b3100f1'
+      - name: 'Run :: Decoding Secrets 65e3f0f3-e0ae-4af7-b478-36071abbb621'
         run: |2-
 
                   if [ ! -x "$(command -v jq)" ]; then
@@ -158,16 +161,8 @@ jobs:
                   fi
                   echo "${{ env.ENCODED_PIPELINE_SECRET }}" | base64 --decode | jq -r 'to_entries[] | "\(.key)=\(.value)"' | while read line; do echo "$line" >> $GITHUB_ENV; echo "::add-mask::${line#*=}"; done
                 
-      - name: 'Run :: Configure AWS credentials 085d72c4-818d-40bc-a8af-b1dfd622a876'
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          role-to-assume: ${{ env.roleARN }}
-          role-session-name: skyu-pipeline-assume-role-session
-          aws-region: ${{ env.region }}
-      - name: 'Run :: Stop EC2 Runner'
-        uses: machulav/ec2-github-runner@v2
-        with:
-          mode: stop
-          github-token: ${{ env.pat }}
-          label: ${{ needs.start-runner.outputs.label }}
-          ec2-instance-id: ${{ needs.start-runner.outputs.ec2-instance-id }}
+      - name: 'Run :: Stop AWS Spot Instance'
+        run: |2-
+
+                aws ec2 terminate-instances --instance-ids ${{ needs.start-runner.outputs.EC2_INSTANCE_ID }}}
+              
